import sys

infile = (open('/Users/lauren/Documents/Phage_sequencing/Phage_5/contigs.fa.fas')).read()


spacers = ['CTGAATGCCGGATGCGCGTTGCTTATCCGGCCTACAAAATTGCAGCGTGTAGGCCT', 'TGCCGCATCCGACAATAACAGCATTGCCTGATGCGACGCTTG', 'CACGGTAACTCCGGGTGGAGAGAGTTGTACGTATAACGACATC', 'AGCGGCACGCTGGATTGAACAAATCCCTGGGC', 'AAACCGAAACACACGATCAATCCGAATATGAG','TTTGGTGACAGTTTTTGTCACTGTTTTGGTGA', 'CTCGACTTTAATTTTTTCGCTGCCCGCTTTTGC', 'ATATGTCAGCAGCCCAAACAG', 'GTCCTCTCTG', 'TGTATGCCGGTATGGAACGGCCAGACGCTGACGTTCGTT', 'AAGTGGCGCAAGAATTTGTAGGCCTGATAAGCGTAGCGCATCAGGCATTTA', 'GAATGGCGCAAGAATCTGTAGGCCTGATAAGCGTAGCGCATCAGGCATTTG', 'CTGTCCCTCTTTGACCATAAATTTGTCCCCAGATAAAAACGCCAAGA', 'TCCCCACACCCCGTATGTCTCCACACCATCAGGCAGGGTA', 'CCGCCGGACGGGGAAACGGGTGTGGCGTCGCGGGCGTGACCTGACGGGA', 'CATTTTCCCTGACACCG', 'ACCTAC', 'GGCGCTGTTTCCCGGTCGCATC', 'CAGTGCACGAATAATGGACAGTT', 'AGGCCATCTTCC', 'CCGCCCTTTTTAAAGTGAATTTTGTGATGCGGTGAATGCGGCTA', 'GAAGGTATATGGGATAATCGCGGATTCAGGTGCTGG', 'GAGCGCACGCGGAACAGTTAAAACCAAAAACAGTGTTATGGGG', 'TCCCCCGATTCAGGTTATAAATGACACAATATCTTGACAACAT', 'CAGGTTGCCGACGCCAATCCGGCTGGTTGCTTCCTTCGTGAAG', 'TTCAGCGCCTGATGCGACGCTGACGCGTCTTATCT', 'CACGCCGCATCCTGTGCCTGATGCGACGCTGGCGCGTCTTATCAGGCCTACAAA', 'TTGGCAGTGTGCCTGATGCGACGCTGTTCGCGTCTTACCAGGCC', 'TCCGGAGCAGGACGGGGTAATCACGCAGGTGGTGATACTGGATGCA', 'GCAAAAGCGGGCAGCGAAAAAATTAAAGTCGAG', 'CTAATTACGGTGGGTTCGGTGGAAGTAGTTTGTAGTATCCAGCGCAGTATCGGGTGATTAGCTCAGCTGGGAGAGCACCTCCCTTAC', 'CTCGGGTCGTTAGCTCAGTTGGTAGAGCAGTTGACTTTT', 'CTAACCTAGTTAGTTGTAGTATCCAGCGTAA', 'CCCCCCCCACCAGCCGCCCATTTACCACAAAT', 'GATGTCGTTATACGTACAACTCTCTCCACCCGGAGTTACCGTG', 'CATGGCTGGTTCCCGGATACAGATGGCGCA', 'CGGACGCAGGATGGTGCGTTCAATTGGACTCGAACCAA', 'CAATGGTGACAAATGCCTGATGCGCTACGCTTATCAGGCCTACAATTCTCGTGCCATTC', 'CAATGGTGACAAATGCCTGATGCGCTACGCTTATCAGGCCTACAGATTCTTGCGCCATTC', 'CAATGGTGATAAATGCCTGATGCGCTACGCTTATCAGGCCTACAAATTCTTGCGCCACTT', 'CAATGGTGACAAATGCCTGATGCGCTACGCTTATCAGGCCTACAGATTCTTGCGCCATTC', 'GAACACAAACCGAAACACACGATCAATCCGAATATGAG', 'GAACACAGCGGCACGCTGGATTGAACAAATCCCTGGGC', 'TTACGCTGGATACTACAACTAACTAGGTTAG', 'AATTGATTAAAAGTCAACTGCTCTACCAACTGAGCTAACGACCCGG', 'AATTGATTAAAAGTCAACTGCTCTACCAACTGAGCTAACGACCCATACGGGTGTTACCTGAAAGATTTCTACTCGGAACCAATCTTTAAAAT', 'GCCCTACGGGCCGTTGCTGACGCAACGTTATCCTTCACGCTTAACATCTGAGTTTGATGTTAAAAT', 'CAAAAAGGGACAGATTTATGGTTAAAAAGGGACAGATTTATGGTTCTTGGCGTTTTTATCTGGGGACAA', 'CTCATCCAGAATGGCATCAACC', 'GTTCAAATCCGGCCCCCGCAACCAATCAAATTTGATGAAGTAAAAGCAGTACGGT', 'TGGGGCAATCAGCAAGAAGGAATATGGGG', 'GATTTTCATGTCGGTAATATACACATTCACCAGG', 'TGCCGCATCCGACAATAACAGCATTGCCTGATGCGACGCTTG', 'TCACCAAAACAGTGACAAAAACTGTCACCAAA', 'CTCATATTCGGATTGATCGTGTGTTTCGGTTT', 'GCCCAGGGATTTGTTCAATCCAGCGTGCCGCT', 'GCAAAAGCGGGCAGCGAAAAAATTAAAGTCGAG', 'CGGACGCAGGATGGTGCGTTCAATTGGACTCGAACCAA', 'TTCAGCGCCTGATGCGACGCTGACGCGTCTTATCT', 'TTGGCAGTGTGCCTGATGCGACGCTGTTCGCGTCTTACCAGGCC', 'CATTTTCCCTGACACCG', 'ACCTAC', 'GGCGCTGTTTCCCGGTCGCATC', 'CAGTGCACGAATAATGGACAGTT', 'AGGCCATCTTCC', 'CCCCATAACACTGTTTTTGGTTTTAACTGTTCCGCGTGCGCTC', 'CACGCCGCATCCTGTGCCTGATGCGACGCTGGCGCGTCTTATCAGGCCTACAAA', 'GAGCGCACGCGGAACAGTTAAAACCAAAAACAGTGTTATGGGG', 'TCCCCCGATTCAGGTTATAAATGACACAATATCTTGACAACAT', 'GAAGGTATATGGGATAATCGCGGATTCAGGTGCTGG', 'CTGTCCCTCTTTGACCATAAATTTGTCCCCAGATAAAAACGCCAAGA', 'CTGAATGCCGGATGCGCGTTGCTTATCCGGCCTACAAAATTGCAGCGTGTAGGCCT', 'AGCGGCACGCTGGATTGAACAAATCCCTGGGC', 'AAACCGAAACACACGATCAATCCGAATATGAG', 'TTTGGTGACAGTTTTTGTCACTGTTTTGGTGA', 'CTCGACTTTAATTTTTTCGCTGCCCGCTTTTGC', 'ATCTCTGGTATATGCCTGATAAGACGCGAATAGCGTCGCATCAGGCACACTGCCAA', 'CGTTAACCCGGCGCAGGTGCTCACCATCGCCAGCATCAGCACCGAA', 'CTGAATGCCGGATGCGCGTTGCTTATCCGGCCTACAAAATTGCAGCGTGTAGGCCT', 'CTCGACTTTAATTTTTTCGCTGCCCGCTTTTGC', 'TGCCGCATCCGACAATAACAGCATTGCCTGATGCGACGCTTG', 'CAAAAAGGGACAGATTTATGGTTAAAAAGGGACAGATTTATGGTTCTTGGCGTTTTTATCTGGGGACAA', '']



for each in spacers:
	lowercase = each.lower()
	#print lowercase
	if lowercase in infile:
		print lowercase
	'''
	answer = infile.find(each)
	print answer
	for line in infile:
		if each in line:
		 print each
		 '''
